# https://github.com/DanySK/Gravis-CI

language: bash

os:
  - linux
  - osx
  - windows
env:
  global:
    - GRAVIS="https://raw.githubusercontent.com/DanySK/Gravis-CI/master/"
    # If you use Windows, you may want to disable Windows Defender. It slows down the builds
    # dramatically, also during cache setup. From a Tanzinul Islam's idea: http://bit.ly/348VPYS,
    # This work around disables it before caching
    - NO_WIN_DEFENDER=$(curl "${GRAVIS}.disable-windows-defender.sh" --output .no-defender.sh && source .no-defender.sh)
  matrix:
    - JDK="openjdk@1.11"
    - JDK="openjdk@1.12"
    - JDK="openjdk@1.13"

before_install:
  - curl "${GRAVIS}.install-jdk-travis.sh" --output ~/.install-jdk-travis.sh
  - source ~/.install-jdk-travis.sh
install:
  - |
    if [ $TRAVIS_OS_NAME = 'windows' ]; then
      choco install python3
      export PYTHON='C:\Python3'*
      export PATH="$PATH:$PYTHON"
    fi
script:
  - ./gradlew --stacktrace --console=plain integrationTest assemble

before_cache:
  - curl "${GRAVIS}.clean_gradle_cache.sh" --output ~/.clean_gradle_cache.sh
  - bash ~/.clean_gradle_cache.sh
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
